config/routes.rb
TwentyTwoClientMessages::Application.routes.draw do

  resources :groups do
    resources :clients    
  end

  match "settings"=>"settings#index"
  match "settings/sync"=>"settings#sync"


  resources :messages


  resources :clients do
    resources :messages#, :controller => "clients_messages"
  end
  
  scope ":type", :type => /(wc|rc)/ do
    resources :clients do     
      member do
        post 'send_message'        
      end  
      get '/new_message' => 'clients#new_message'
    end
    resources :messages
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get '/balance' => "home#balance"
  devise_for :users
  resources :users

end

app/models/message.rb
# encoding: utf-8
class Message < ActiveRecord::Base
  require 'nokogiri'
  attr_accessible :status, :text, :messageble_id, :messageble_type

  belongs_to :messageble

  default_scope { order('id DESC') }

  MESSAGE_STATUSES =
  {
    "DELIVERED" => "все части сообщения успешно доставлены получателю",
    "EXPIRED" => "Срок жизни сообщения вышел, сообщения не доставлено получателю",
    "UNDELIV" => "Сообщение не может быть доставлено. Чаще всего эта ошибка возникает, когда номер абонента не верен, либо абонент отключен",
    "ALFANAMELIMITED" => "Сообщение не может быть отправлено абоненту Life :), так как Альфаимя ограничено",
    "STOPED" => "Сообщение остановлено системой. Чаще всего это происходит, если у клиента недостаточно средств для отправки сообщения",
    "USERSTOPED" => "Сообщение остановлено пользователем через WEB интерфейс",
    "ERROR" => "Системная ошибка при отправке сообщения",
    "PENDING" => "Сообщение в очереди на отправку",
    "SENT" => "Сообщение отправлено абоненту. Ожидается статус сообщения от оператора"
  }

  def recipients
    rec = []
    node_set = Nokogiri::XML(request)    
    node_set.xpath('request/message/recipient').each do |recipient|
      rec << recipient.content
    end
    rec
  end

  def recipients_status
    Hash[*recipients.map{|rec| [rec,SMS.check_status(campaign_id, rec)]}.flatten]
  end

  def recipients_by_status(status)
    recipients_status.find_all{ |key, value| value == status }
  end

  def client_type?
    self.messageble_type=='Client'
  end

  def group_type?
    self.messageble_type=='Group'
  end

  def campaign_id
    node_set = Nokogiri::XML(response)
    campaignID = node_set.xpath('/message/state').first['campaignID']
  end

  before_create do |message|
    case message.messageble_type
      when 'Client'
        client = Client.find(message.messageble_id)
        recipients = [client.phone]
        result, request, response = SMS.send_sms(message.text, recipients, 'desc')
        message.status = result
        message.request = request
        message.response = response
      when 'Group'
        recipients = Group.find(message.messageble_id).clients.pluck(:phone)
        result, request, response = SMS.send_sms(message.text, recipients, 'desc')
        message.status = result
        message.request = request
        message.response = response
      else 
        # false
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  inherit_resources
  belongs_to :client, :group, :polymorphic => true, :optional => true
  respond_to :js

  before_filter :authenticate_user!
  before_filter  do
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.haml
= simple_form_for @message, :html => { :class => 'form-horizontal' } do |f|
  = f.input :campaign_id
  = f.input :text
  = f.input :messageble_id
  = f.input :messageble_type
  = f.input :status
  = f.input :request
  = f.input :response
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), messages_path, :class => 'btn'

app/views/messages/_show.html.haml
:css
  .mes_success{
    background-color: #DFF0D8;border-color: #D6E9C6;color: #468847;
  }

.mes_success.row
  %span.span6= link_to @message.text, message_path(@message), :target=>'_blanck'
  %span.span3= @message.created_at.strftime('%d-%m-%Y %H:%M')
  %span.span3= @message.status

app/views/messages/create.js.haml
:plain
  $('.row').removeClass('mes_success');
  $('.messages').prepend("#{escape_javascript(render :partial=>'show')}");
              

app/views/messages/edit.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/messages/index.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:text)
      %th= model_class.human_attribute_name(:status)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @messages.each do |message|
      %tr
        %td= link_to message.text, message_path(message)
        %td= message.status
        %td= message.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(message), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(message), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_message_path, :class => 'btn btn-primary'

app/views/messages/new.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/messages/show.html.haml
- model_class = Message
.page-header
  %h1=t '.title', :default => model_class.model_name.human
.tabbable
%ul.nav.nav-tabs
  %li.active
    %a(href="#tab1" data-toggle="tab") Основная информация
  %li
    %a(href="#tab2" data-toggle="tab") Request
  %li
    %a(href="#tab3" data-toggle="tab") Response
  %li
    %a(href="#tab4" data-toggle="tab") Статусы сообщнения
.tab-content
  #tab1.tab-pane.active
    %p
      %strong= model_class.human_attribute_name(:campaign_id) + ':'
      %br
      = @message.campaign_id
    %p
      %strong= model_class.human_attribute_name(:text) + ':'
      %br
      = @message.text
    %p
      %strong= model_class.human_attribute_name(:messageble_id) + ':'
      %br
      = @message.messageble_id
    %p
      %strong= model_class.human_attribute_name(:messageble_type) + ':'
      %br
      = @message.messageble_type
    %p
      %strong= model_class.human_attribute_name(:status) + ':'
      %br
      = @message.status  
    

    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), messages_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_message_path(@message), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), message_path(@message), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  #tab2.tab-pane
    %p
      %strong= model_class.human_attribute_name(:request) + ':'
      %br
      =text_area_tag 'request', @message.request, :rows => 50, :style=>"width:80%;"
  #tab3.tab-pane
    %p
      %strong= model_class.human_attribute_name(:response) + ':'
      %br
      =text_area_tag 'response', @message.response, :rows => 50, :style=>"width:80%;"
  #tab4.tab-pane
    // - Message::MESSAGE_STATUSES.each_pair do |key, value|
    //   %p= "#{value} - #{@message.recipients_by_status(key).size}"
    // - @message.recipients_status.each_pair do |key, value|
    //   %p= "#{key} - #{Message::MESSAGE_STATUSES[value]}"