config/routes.rb
TwentyTwoClientMessages::Application.routes.draw do

  resources :groups do
    resources :clients    
  end

  match "settings"=>"settings#index"
  match "settings/sync"=>"settings#sync"


  resources :messages


  resources :clients do
    resources :messages#, :controller => "clients_messages"
  end
  
  scope ":type", :type => /(wc|rc)/ do
    resources :clients do     
      member do
        post 'send_message'        
      end  
      get '/new_message' => 'clients#new_message'
    end
    resources :messages
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get '/balance' => "home#balance"
  devise_for :users
  resources :users

end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :description, :name

  has_and_belongs_to_many :clients, :uniq => true

  has_many :messages, :as => :messageble
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  inherit_resources
  respond_to :html

  before_filter :authenticate_user!
  before_filter  do
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.haml
= simple_form_for @group, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :description
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), groups_path, :class => 'btn'

app/views/groups/edit.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/groups/index.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:description)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @groups.each do |group|
      %tr
        %td= link_to group.name, group_path(group)
        %td= group.description
        %td=l group.created_at
        %td
          = link_to 'Show clients', group_clients_path(group), :class => 'btn btn-mini'
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(group), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(group), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_group_path, :class => 'btn btn-primary'

app/views/groups/new.html.haml
- model_class = Group
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/groups/show.html.haml
.tabbable
%ul.nav.nav-tabs
  %li.active
    %a(href="#tab1" data-toggle="tab") Group information
  %li
    %a(href="#tab2" data-toggle="tab") Messages
.tab-content
  #tab1.tab-pane.active
    - model_class = Group
    .page-header
      %h1=t '.title', :default => model_class.model_name.human

    %p
      %strong= model_class.human_attribute_name(:name) + ':'
      %br
      = @group.name
    %p
      %strong= model_class.human_attribute_name(:description) + ':'
      %br
      = @group.description

    .form-actions
      = link_to 'Show clients', group_clients_path(@group), :class => 'btn'
      = link_to t('.back', :default => t("helpers.links.back")), groups_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_group_path(@group), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), group_path(@group), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  #tab2.tab-pane
    =render :partial=>'shared/messages', :locals=>{:messages=>@group.messages}
    =render :partial=>'shared/new_message', :locals=>{:message=>@group.messages.new}