config/routes.rb
TwentyTwoClientMessages::Application.routes.draw do

  resources :groups do
    resources :clients    
  end

  match "settings"=>"settings#index"
  match "settings/sync"=>"settings#sync"


  resources :messages


  resources :clients do
    resources :messages#, :controller => "clients_messages"
  end
  
  scope ":type", :type => /(wc|rc)/ do
    resources :clients do     
      member do
        post 'send_message'        
      end  
      get '/new_message' => 'clients#new_message'
    end
    resources :messages
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get '/balance' => "home#balance"
  devise_for :users
  resources :users

end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :account_balance, :advance_payment, :is_wholesale_customer, :name, :phone, :city, :total_amount_of_purchases, :remote_id

  self.per_page = 20

  has_many :messages, :as => :messageble
  has_and_belongs_to_many :groups, :uniq => true  

  scope :wholesale_customers, where(:is_wholesale_customer=>1)
  scope :retail_customers, where(:is_wholesale_customer=>0)

  def wholesale_customer?
    is_wholesale_customer
  end

  def retail_customer?
    !wholesale_customer?
  end


  after_create do
    if self.wholesale_customer?
      self.groups<<Group.find(1)
    else
      self.groups<<Group.find(2)
    end
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  inherit_resources
  belongs_to :group, :optional => true

  before_filter :authenticate_user!
  before_filter  do
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
  end

  protected
  def collection
    @clients ||= end_of_association_chain.paginate(:page => params[:page])
  end
  
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.haml
= simple_form_for @client, :html => { :class => 'form-horizontal' } do |f|
  = f.input :name
  = f.input :phone
  = f.input :city
  = f.input :account_balance
  = f.input :advance_payment
  = f.input :total_amount_of_purchases
  = f.input :is_wholesale_customer
  = f.input :remote_id
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), clients_path, :class => 'btn'

app/views/clients/edit.html.haml
- model_class = Client
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/clients/index.html.haml
- model_class = Client
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize
= will_paginate @clients, :renderer => BootstrapPaginationHelper::LinkRenderer

= link_to t('.new', :default => t("helpers.links.new")), new_client_path, :class => 'btn btn-primary'
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:phone)
      %th= model_class.human_attribute_name(:city)
      %th= model_class.human_attribute_name(:account_balance)
      %th= model_class.human_attribute_name(:advance_payment)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @clients.each do |client|
      %tr
        %td= link_to client.name, client_path(client)
        %td= client.phone
        %td= client.city
        %td= client.account_balance
        %td= client.advance_payment
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_client_path(client), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), client_path(client), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
%br
= will_paginate @clients, :renderer => BootstrapPaginationHelper::LinkRenderer

= link_to t('.new', :default => t("helpers.links.new")), new_client_path, :class => 'btn btn-primary'

app/views/clients/new.html.haml
- model_class = Client
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human
= render :partial => "form"

app/views/clients/show.html.haml
.tabbable
%ul.nav.nav-tabs
  %li.active
    %a(href="#tab1" data-toggle="tab") Client information
  %li
    %a(href="#tab2" data-toggle="tab") Messages
.tab-content
  #tab1.tab-pane.active
    - model_class = Client
    .page-header
      %h1=t '.title', :default => model_class.model_name.human

    %p
      %strong= model_class.human_attribute_name(:name) + ':'
      %br
      = @client.name
    %p
      %strong= model_class.human_attribute_name(:phone) + ':'
      %br
      = @client.phone
    %p
      %strong= model_class.human_attribute_name(:city) + ':'
      %br
      = @client.city
    %p
      %strong= model_class.human_attribute_name(:account_balance) + ':'
      %br
      = @client.account_balance
    %p
      %strong= model_class.human_attribute_name(:advance_payment) + ':'
      %br
      = @client.advance_payment
    %p
      %strong= model_class.human_attribute_name(:total_amount_of_purchases) + ':'
      %br
      = @client.total_amount_of_purchases
    %p
      %strong= model_class.human_attribute_name(:is_wholesale_customer) + ':'
      %br
      = @client.is_wholesale_customer
    %p
      %strong= model_class.human_attribute_name(:remote_id) + ':'
      %br
      = @client.remote_id

    .form-actions
      = link_to t('.back', :default => t("helpers.links.back")), clients_path, :class => 'btn'
      = link_to t('.edit', :default => t("helpers.links.edit")), edit_client_path(@client), :class => 'btn'
      = link_to t('.destroy', :default => t("helpers.links.destroy")), client_path(@client), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'
  #tab2.tab-pane
    =render :partial=>'shared/messages', :locals=>{:messages=>@client.messages}
    =render :partial=>'shared/new_message', :locals=>{:message=>@client.messages.new}