config/routes.rb
TwentyTwoClientMessages::Application.routes.draw do

  resources :groups do
    resources :clients    
  end

  match "settings"=>"settings#index"
  match "settings/sync"=>"settings#sync"


  resources :messages


  resources :clients do
    resources :messages#, :controller => "clients_messages"
  end
  
  scope ":type", :type => /(wc|rc)/ do
    resources :clients do     
      member do
        post 'send_message'        
      end  
      get '/new_message' => 'clients#new_message'
    end
    resources :messages
  end

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  get '/balance' => "home#balance"
  devise_for :users
  resources :users

end

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Twenty Two Client Messages", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to 'Logout', destroy_user_session_path, :method=>'delete'
  - else
    %li
      = link_to 'Login', new_user_session_path
  - if user_signed_in?
    %li
      = link_to 'Edit account', edit_user_registration_path
    - if current_user.has_role? :admin
      %li
        = link_to 'Admin', users_path
      %li
        = link_to 'Настройки', settings_path
      %li
        = link_to 'Баланс', balance_path
      %li
        = link_to 'Clients', clients_path
      %li
        = link_to 'Сообщения', messages_path
      %li
        = link_to 'Группы клиентов', groups_path
  - else
    %li
      = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "Twenty Two Client Messages"
      %meta{:content => content_for?(:description) ? yield(:description) : "Twenty Two Client Messages", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .content
        = render 'layouts/messages'
        = yield
        %footer
      / ! end of .container
    / ! end of #main